spring.application.name=YathriGlobe-api-gateway
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Enable discovery-based routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://YATHRIGLOBE-AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=user-profile-service
spring.cloud.gateway.routes[1].uri=lb://YATHRIGLOBE-USER-PROFILE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/profiles/**

spring.cloud.gateway.routes[2].id=destination-service
spring.cloud.gateway.routes[2].uri=lb://YATHRIGLOBE-DESTINATION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/destinations/**

spring.cloud.gateway.routes[3].id=trip-service
spring.cloud.gateway.routes[3].uri=lb://YATHRIGLOBE-TRIP-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/trips/**

spring.cloud.gateway.routes[4].id=booking-service
spring.cloud.gateway.routes[4].uri=lb://YATHRIGLOBE-BOOKING-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/bookings/**

spring.cloud.gateway.routes[5].id=review-service
spring.cloud.gateway.routes[5].uri=lb://YATHRIGLOBE-REVIEW-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/reviews/**



jwt.secret=yathriglobe_secret_key_which_is_very_secure_256bit
