spring.application.name=YATHRIGLOBE-TRIP-SERVICE
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/yathriglobe_trip
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

jwt.secret=yathriglobe_secret_key_which_is_very_secure_256bit